export const jobs = [
  {
    id: "seaside-pier",
    company: "Seaside Pier Café",
    city: "Ocean City",
    state: "Maryland",
    stateCode: "MD",
    industry: "Food service",
    role: "Food service",
    wage: "$15/ч + чаевые",
    baseWage: 15,
    hours: "32–40 ч/нед.",
    housing: "Помощь с размещением",
    housingCost: "Уточнить",
    transport: "Пешком до работы",
    sponsorRoute: "Нужна проверка",
    potential: "Хороший",
    note: "Подходит тем, кому важны чаевые и жизнь у океана.",
    questions: ["Какой средний доход с чаевыми?", "Есть ли гарантированные часы?", "Какая цена жилья после заселения?"],
    tags: ["чаевые", "пляж", "пешком"]
  },
  {
    id: "cape-shore",
    company: "Cape Shore Inn",
    city: "Hyannis",
    state: "Massachusetts",
    stateCode: "MA",
    industry: "Hotel",
    role: "Housekeeping",
    wage: "$16/ч",
    baseWage: 16,
    hours: "35–40 ч/нед.",
    housing: "Организовано работодателем",
    housingCost: "$170/нед.",
    transport: "10 минут пешком",
    sponsorRoute: "Нужна проверка",
    potential: "Стабильный",
    note: "Ровные часы и понятная стоимость жилья — хорошая база для расчёта бюджета.",
    questions: ["Что входит в $170/нед.?", "Есть ли депозит?", "Какие даты заезда и выезда?"],
    tags: ["отель", "жильё", "Cape Cod"]
  },
  {
    id: "boardwalk-ride",
    company: "Boardwalk Ride Co.",
    city: "Wildwood",
    state: "New Jersey",
    stateCode: "NJ",
    industry: "Park",
    role: "Ride operator",
    wage: "$15.50/ч",
    baseWage: 15.5,
    hours: "30–38 ч/нед.",
    housing: "Жильё не включено",
    housingCost: "Искать отдельно",
    transport: "Нужна проверка",
    sponsorRoute: "Self-placement / vetting",
    potential: "Средний",
    note: "Классическая курортная локация, но жильё и дорогу нужно посчитать заранее.",
    questions: ["Есть ли список рекомендованного жилья?", "Нужна ли машина?", "Как часто бывают дополнительные смены?"],
    tags: ["аттракционы", "пляж", "self-placement"]
  },
  {
    id: "pine-ridge",
    company: "Pine Ridge Lodge",
    city: "Wisconsin Dells",
    state: "Wisconsin",
    stateCode: "WI",
    industry: "Resort",
    role: "Guest services",
    wage: "$15.50/ч",
    baseWage: 15.5,
    hours: "32–40 ч/нед.",
    housing: "Staff housing",
    housingCost: "$145/нед.",
    transport: "На территории",
    sponsorRoute: "Нужна проверка",
    potential: "Стабильный",
    note: "Компактная resort-локация: удобно, если не хочется зависеть от машины.",
    questions: ["Сколько человек в комнате?", "Включены ли utilities?", "Можно ли брать extra shifts?"],
    tags: ["resort", "жильё", "без машины"]
  },
  {
    id: "summit-trail",
    company: "Summit Trail Rentals",
    city: "Estes Park",
    state: "Colorado",
    stateCode: "CO",
    industry: "Resort",
    role: "Rental attendant",
    wage: "$16.25/ч",
    baseWage: 16.25,
    hours: "32–40 ч/нед.",
    housing: "Жильё не включено",
    housingCost: "Уточнить",
    transport: "Нужна проверка",
    sponsorRoute: "Self-placement / vetting",
    potential: "Выше среднего",
    note: "Выше ставка, но только точная цена жилья покажет реальный остаток за сезон.",
    questions: ["Есть ли staff housing рядом?", "Какой транспорт до работы?", "Какая дата начала сезона?"],
    tags: ["горы", "активности", "self-placement"]
  },
  {
    id: "harbor-ice-cream",
    company: "Harbor Ice Cream",
    city: "Rehoboth Beach",
    state: "Delaware",
    stateCode: "DE",
    industry: "Food service",
    role: "Counter staff",
    wage: "$15/ч + чаевые",
    baseWage: 15,
    hours: "30–36 ч/нед.",
    housing: "Жильё рядом",
    housingCost: "Уточнить",
    transport: "Пешком / велосипед",
    sponsorRoute: "Нужна проверка",
    potential: "Хороший",
    note: "Небольшой сезонный формат: оцени не только ставку, но и фактический поток гостей.",
    questions: ["Какой график в высокий сезон?", "Как распределяются чаевые?", "Есть ли вечерние смены?"],
    tags: ["чаевые", "берег", "велосипед"]
  },
  {
    id: "misty-harbor",
    company: "Misty Harbor Market",
    city: "Bar Harbor",
    state: "Maine",
    stateCode: "ME",
    industry: "Retail",
    role: "Store associate",
    wage: "$15.25/ч",
    baseWage: 15.25,
    hours: "32–38 ч/нед.",
    housing: "Нужна самостоятельная проверка",
    housingCost: "Уточнить",
    transport: "Нужна проверка",
    sponsorRoute: "Self-placement / vetting",
    potential: "Средний",
    note: "Хорошая локация для тех, кто готов тщательно проверить жильё и транспорт до оффера.",
    questions: ["Можно ли жить без машины?", "Как далеко жильё?", "Какие расходы на транспорт?"],
    tags: ["ретейл", "Maine", "проверить жильё"]
  },
  {
    id: "smoky-trails",
    company: "Smoky Trails Lodge",
    city: "Gatlinburg",
    state: "Tennessee",
    stateCode: "TN",
    industry: "Hotel",
    role: "Front desk assistant",
    wage: "$15.75/ч",
    baseWage: 15.75,
    hours: "34–40 ч/нед.",
    housing: "Организовано работодателем",
    housingCost: "$155/нед.",
    transport: "Staff shuttle",
    sponsorRoute: "Нужна проверка",
    potential: "Стабильный",
    note: "Комбинация жилья и шаттла делает предложение проще для первого самостоятельного сезона.",
    questions: ["Сколько стоят utilities?", "Есть ли вечерний shuttle?", "Какой уровень английского нужен?"],
    tags: ["отель", "шаттл", "жильё"]
  }
];

export const destinations = [
  { rank: 1, state: "New Jersey", places: "Ocean City · Wildwood · Seaside Heights" },
  { rank: 2, state: "Massachusetts", places: "Cape Cod · Hyannis · Falmouth" },
  { rank: 3, state: "Maryland", places: "Ocean City" },
  { rank: 4, state: "South Carolina", places: "Myrtle Beach" },
  { rank: 5, state: "Wisconsin", places: "Wisconsin Dells · Lake Delton" },
  { rank: 6, state: "Alaska", places: "Anchorage · Denali · Seward" },
  { rank: 7, state: "Colorado", places: "Estes Park · Aspen · Vail" },
  { rank: 8, state: "Tennessee", places: "Gatlinburg · Pigeon Forge · Sevierville" },
  { rank: 9, state: "Delaware", places: "Rehoboth Beach · Bethany Beach" },
  { rank: 10, state: "Maine", places: "Bar Harbor · Old Orchard Beach" }
];

export const sponsorOptions = [
  "Не выбран",
  "CIEE",
  "InterExchange",
  "Greenheart Exchange",
  "Alliance Abroad Group",
  "GeoVisions"
];
